version: "3.9"

services:
  app:
    container_name: currency-exchanger
    build:
      context: .
    volumes:
      - ./app:/app
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_BUCKET=${AWS_BUCKET}